### ISSUE TITLE
Positions freezing but times resume

### ISSUE THREAD

**Issue by NotGeo15** [GrygrFlzr/are-we-there-yet#8]
Every time I redeploy everything is up to date.. and that's it. There are no POSITION updates after that redeploy, but, yet the times update just fine. The embed isn't just straight-up failing, it's still working shown by the times but position updates don't seem to work unless you redeploy again.

**Comment by NotGeo15** [comment]
Deschtimes is sending the post request just it's hit a roadblock here.

**Comment by GrygrFlzr** [comment]
Is this still an issue with the latest build?

**Comment by NotGeo15** [comment]
Nope fixed. Sorry about the uber late reply I'll close this ticket.
