### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by NotGeo15** [GrygrFlzr/are-we-there-yet#9]
This has been an issue for a while so I don't need to explain everything. Long story short the themes aren't working. Someone's hypothesis on this bug is "$page.query.get(..) returns null for prerendered pages" as shown in [this sveltejs issue thread ](https://github.com/sveltejs/kit/issues/669). [Here's a video demonstrating it](https://cdn.discordapp.com/attachments/380186959911321607/872525042460811314/bug.mp4) by that same person, and [here's a video of the issue in action](https://cdn.discordapp.com/attachments/380186959911321607/872357932304584745/2021-08-04_01-57-17.mp4). Not sure how to fix this since I don't know this language of coding but I hope these resources can speed up the process of fixing it.

**Comment by GrygrFlzr** [comment]
Fixed by d8bda41
